name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - latest
      - v*

jobs:

  ghcr:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang mold
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure \
            --enable-developer-mode \
            --disable-dependency-checks \
            CHECKMAKE=false RUFF=false TYPOS=false
      - name: Publish Docker Image to GH Container Registry
        run: |
          make docker-build-push
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPO: ${{ github.repository }}
          DOCKER_TAG: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PAT: ${{ secrets.CR_FONTSHIP }}
