name: Rust Lint

on: [ "pull_request", "push" ]

jobs:

  rustfmt:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: |
          git ls-files '*.rs' '*.rs.in' | xargs rustfmt --check --config skip_children=true

  clippy:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup system dependencies
        run: |
          sudo apt-get install clang mold
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: -- -D warnings
