name: Rust Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: |
          sudo apt-get install clang mold
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
