name: Cargo Bloat

on: [ "pull_request" ]

jobs:

  cargo_bloat:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Run cargo bloat
        # https://github.com/orf/cargo-bloat-action/pull/302
        # uses: orf/cargo-bloat-action@v1
        uses: Kobzol/cargo-bloat-action@github-actions-cache
        with:
          token: ${{ github.token }}
