name: Versioning

on:
  release:
    types: [ released ]

jobs:
  actions-tagger:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
